<?php
/**
 * Código fuente desarrollado por Franklin Moreno e Hiram González
 * Contacto:
 *  hiramjgonzalez98@gmail.com
 *  cfranklinmoreno@gmail.com
 */

abstract class professor_options extends cuenta {

    protected $idProfesor;

    public function __construct($idCuenta, $contraseña){

        parent::__construct($idCuenta, $contraseña);

    }

    /**
     * @deprecated
     */
    public function establecer_id()
    {
        parent::establecer_id(); // TODO: Change the autogenerated stub
    }

    public function login()
    {
        return parent::login(); // TODO: Change the autogenerated stub
    }

    public function actContra()
    {
        return parent::actContra(); // TODO: Change the autogenerated stub
    }

    public static function recuperar()
    {
        return parent::recuperar(); // TODO: Change the autogenerated stub
    }

    public function comprobar_contra()
    {
        return parent::comprobar_contra(); // TODO: Change the autogenerated stub
    }

    public function sumar($numero, $tabla, $codigo, $referencia)
    {
        parent::sumar($numero, $tabla, $codigo, $referencia); // TODO: Change the autogenerated stub
    }


    public function alumn_search($id){

    }

}